compute : compute.o proc-common.o tree.o
	gcc -o compute compute.o proc-common.o tree.o
	
compute.o : compute.c
	gcc -c compute.c

proc-common.o : proc-common.c
	gcc -c proc-common.c

tree.o : tree.c
	gcc -c tree.c
