third : third.o proc-common.o tree.o
	gcc -o third third.o proc-common.o tree.o
	
third.o : third.c
	gcc -c third.c

proc-common.o : proc-common.c
	gcc -c proc-common.c

tree.o : tree.c
	gcc -c tree.c

