second : second.o proc-common.o tree.o
	gcc -o second second.o proc-common.o tree.o

second.o : second.c
	gcc -c second.c

proc-common.o : proc-common.c
	gcc -c proc-common.c

tree.o : tree.c
	gcc -c tree.c
